### ISSUE TITLE
Improving panic!

### ISSUE THREAD

**Issue by hasanOryx** [anvie/dotext#1]
Thanks for this great crate at the beginning.

I've the below code that open a file, and search for specific words on it:

```
use std::io::Read;

extern crate argparse;
use argparse::{ArgumentParser, Store};

extern crate dotext;
use dotext::*;

extern crate regex;
use regex::RegexSet;

fn main(){
    let mut path = String::new();
    let mut skills = String::new();
    {
        let mut ap = ArgumentParser::new();
        ap.refer(&mut path)
            .add_option(&["-p", "--path"], Store,
            "Path to the file to be read");
        ap.refer(&mut skills)
            .add_option(&["-s", "--skills"], Store,
            "Skills / Experience required");

        ap.parse_args_or_exit();
    }

    let searches: Vec<&str> = skills.split_whitespace().collect(); //.split(",")
    //let searches = skills.split(",").collect::<Vec<&str>>();

    let set = RegexSet::new(&searches).unwrap();

//    let mut file = Docx::open("samples/sample.docx").unwrap();
    let mut file = Docx::open(path).expect("Cannot open file");
    let mut isi = String::new();
    let _ = file.read_to_string(&mut isi);

    if set.is_match(&isi){
        let matches: Vec<_> = set.matches(&isi).into_iter().collect();
        let exact_matches = matches.iter().
                                    map(|num| searches[*num]).collect::<Vec<&str>>();
        println!("Out of {} requirements, the below {} matches had been found:",
                set.len(), matches.len());
        for x in exact_matches {
                println!("{}", x );
        }
    } else {
            println!("No matches found");
    }
}
```

It is working a expected when the file is existed:

> Hasans-Air:debug hasan$ ./ufg -p "samples/sample.docx" -s "factorial planning carborundum"
> Out of 3 requirements, the below 2 matches had been found:
> factorial
> carborundum

But if the file is not there, the error message is annoying to appear in the runtime, how can I capture this panic in the code it self, so I can notify the user and avoid unexpected exit of the program.

> Hasans-Air:debug hasan$ ./ufg -s "factorial Hasan Yousef carborundum"
> thread 'main' panicked at 'Cannot open file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by anvie** [comment]
`Docx::open()` return type is `io::Result<Docx>` you should handle exception using `.is_err()` as the conditional statement, don't use `.expect()` it will raise exception when expected condition not meet.

I prefer use this approach instead:

```rust
let rv = Docx::open(&path);
if rv.is_err(){
    eprintln!("Cannot open file: {} ({})", path, rv.err().unwrap());
    return;
}
let mut file = rv.unwrap();
```
